FROM mcr.microsoft.com/powershell:latest

ADD "https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-win64.zip" nvim.zip
# RUN powershell -command "Expand-Archive -Path nvim.zip -DestinationPath C:\nvim"

CMD powershell -NoLogo