name: Test workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    name: "Test something"
    steps:
      - uses: actions/checkout@v3
      - name: Run setup.ps1
        run: |
          (iwr https://raw.githubusercontent.com/BusHero/system.config/refs/heads/master/Bootstrap.ps1).Content | Invoke-Expression
      # - name: setup path
      #   run: |
      #     Write-Output "$($env:LocalAppData)\Programs\oh-my-posh\bin" | Out-File `
      #       -FilePath $env:GITHUB_PATH `
      #       -Encoding utf8 `
      #       -Append
      # - name: Run test.ps1
      #   run: .\test.ps1
