name: Test workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    name: "Test something"
    steps:
      - uses: actions/checkout@v3
      - name: Run setup.ps1
        run: .\setup.ps1
      - name: Run test.ps1
        run: |
          if (Test-Path "$(${env:ProgramFiles(x86)})\oh-my-posh") {
            echo "%ProgramFiles(x86)%\oh-my-posh\bin" | Out-File `
              -FilePath $env:GITHUB_PATH `
              -Encoding utf8 `
              -Append
          }
          elseif (Test-Path "$($env:LOCALAPPDATA)\Programs\oh-my-posh") {
            echo '%LOCALAPPDATA%\Programs\oh-my-posh\bin' | Out-File `
              -FilePath $env:GITHUB_PATH `
              -Encoding utf8 `
              -Append
          }
          .\test.ps1
