name: Test workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    name: "Test something"
    steps:
      - uses: actions/checkout@v3
      - name: Run setup.ps1
        run: |
          .\powershell\setup.ps1
          if (Test-Path "$(${env:ProgramFiles(x86)})\oh-my-posh") {
            echo "$(${env:ProgramFiles(x86)})\oh-my-posh\bin" | Out-File `
              -FilePath $env:GITHUB_PATH `
              -Encoding utf8 `
              -Append
          }
          elseif (Test-Path "$($env:LOCALAPPDATA)\Programs\oh-my-posh") {
            echo "$($env:LOCALAPPDATA)\Programs\oh-my-posh\bin" | Out-File `
              -FilePath $env:GITHUB_PATH `
              -Encoding utf8 `
              -Append
          }
      - name: Run tests.ps1
        run: |
          . $PROFILE.CurrentUserAllHosts
          .\powershell\test.ps1
        shell: pwsh -NoProfile -Command ". '{0}'"
