name: Test workflow
on: push
jobs:
  test:
    runs-on: windows-latest
    name: "Test something"
    steps:
      - uses: actions/checkout@v3
      - name: Run setup.ps1
        run: |
          .\setup.ps1
      - name: setup path
        run: |
          Write-Output "$($env:LocalAppData)\Programs\oh-my-posh\bin" | Out-File `
            -FilePath $env:GITHUB_PATH `
            -Encoding utf8 `
            -Append
      - name: Run test.ps1
        run: .\test.ps1
